name: 'Deploy to GitHub Pages'
description: 'This action will handle the deployment process of your project to GitHub Pages.'
author: 'liangdongin'

runs:
  jobs:
  build-and-deploy:
    steps:
    - name: build
      uses: .github/workflows/build

branding:
  icon: 'git-commit'
  color: 'orange'

inputs:
  BRANCH:
    description: 'This is the branch you wish to deploy to, for example gh-pages or docs.'
    required: true

  FOLDER: 
    description: 'The folder in your repository that you want to deploy. If your build script compiles into a directory named build you would put it here. Folder paths cannot have a leading / or ./. If you wish to deploy the root directory you can place a . here.'
    required: true

  TARGET_FOLDER:
    description: 'If you would like to push the contents of the deployment folder into a specific directory on the deployment branch you can specify it here.'
    required: false

  BASE_BRANCH:
    description: 'The base branch of your repository which you would like to checkout prior to deploying. This defaults to the current commit SHA that triggered the build followed by master if it does not exist. This is useful for making deployments from another branch, and also may be necessary when using a scheduled job.'
    required: false
outputs:
  DEPLOYMENT_STATUS:
    description: 'The status of the deployment that indicates if the run failed or passed. Possible outputs include: success|failed|skipped'