name: GitHub Actions Build and Deploy
on:
  push:
    branches:
      - blog-source
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.1

    - name: Build and Deploy
      uses: liangdongin/blog@blog-source
      env:
        ACCESS_TOKEN: ${{ secrets.GH_TOKEN }}
        BRANCH: master
        FOLDER: public
        BUILD_SCRIPT: npm install && hexo g