name: GitHub Actions Build and Deploy
on:
  push:
    branches:
      - blog-source
jobs:
  build-and-deploy:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        repository: 'liangdongin/blog'
        ref: 'blog-source'
        token: ${{ secrets.GH_TOKEN }}
    - name: Install and Build 
      run: |
          # install hexo env
          node -v
          git submodule update --init --recursive
          \cp themes_config.yml themes/BlueLake/_config.yml
          npm install
          sudo npm install hexo-cli -g
          npm install hexo-generator-feed --save
          npm install hexo-generator-sitemap --save
          npm install hexo-generator-json-content --save
          npm uninstall hexo-generator-index --save
          npm install hexo-generator-index-pin-top --save
          hexo g
          cd public
          ls -ahl
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        ACCESS_TOKEN: ${{ secrets.GH_TOKEN }}
        BRANCH: master
        FOLDER: public
        CLEAN: true # Automatically remove deleted files from the deploy branch
    - name: Pull
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          whoami
          ls -al