name: GitHub Actions Build and Deploy
on:
  push:
    branches:
      - blog-source
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        repository: 'liangdongin/blog'
        ref: 'blog-source'
        token: ${{ secrets.GH_TOKEN }}
    - name: Install and Build 
      run: |
          npm install hexo
          npm i --save hexo-wordcount
          npm install
          hexo g
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        ACCESS_TOKEN: ${{ secrets.GH_TOKEN }}
        BRANCH: master
        FOLDER: public
        CLEAN: true # Automatically remove deleted files from the deploy branch